all:
	gcc --std=c99 --pedantic -Wall Main_programm.c -o Main_programm.exe
#gcc --std=c99 --pedantic -Wall Main_programm.c -o Main_programm.exe & Main_programm &
#del /q d:\D\Github\Laboratory-works\LW23\Main_programm.exe 
#то, чем я запустил прогу в командной строке