#https:\\itsecforu.ru\2022\09\14\%F0%9F%90%A7-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B0%D0%B1%D1%81%D0%BE%D0%BB%D1%8E%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D1%83%D1%82%D0%B8-%D0%BA-%D1%84%D0%B0%D0%B9%D0%BB%D1%83\
#https:\\losst.pro\gerp-poisk-vnutri-fajlov-v-linux?ysclid=ltfexf602f470616812
#https:\\habr.com\ru\companies\ruvds\articles\327530\